version: '3'

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000"
    expose:
      - 3000

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    expose:
      - "9000"
    volumes:
      - /opt/backend:/var/www/html/storage/app/public/

  mysql:
    image: bitnami/mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
#    healthcheck:
#      test: bash -c "[ -f /bitnami/mysql/.mysql_initialized ]" && mysql -uMYSQL_USER -pMYSQL_PASSWORD MYSQL_DATABASE --silent --execute "SHOW TABLES;"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_BIND_ADDRESS=0.0.0.0

volumes:
  mysql-data:
    external: false
