version: '3'

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
    ports:
      - "80:80"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    working_dir: /var/www/frontend
    tty: true
    ports:
      - "3000"
    expose:
      - 3000

#  mysql:
#    image: mysql:8.0
#    volumes:
#      - mysql-data:/var/lib/mysql
#    ports:
#      - ${MYSQL_PORT}:3306
#    environment:
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

#volumes:
#  mysql-data:
#    external: true
